"""
Production Postgres RAG Retriever implementing the RAGRetriever interface.

Queries KnowledgeChunkRepository using vector embeddings generated by EmbeddingProvider.
"""

from __future__ import annotations

import asyncio
import logging
import time
from typing import Any, Dict, List, Optional
from sqlalchemy.orm import Session

from app.ai.providers.base import EmbeddingProvider
from app.ai.rag.base import RAGRetriever
from app.ai.rag.query_processor import QueryProcessor
from app.ai.rag.reranker import DeterministicReranker
from app.ai.rag.faiss_store import FAISSVectorStore
from app.ai.schemas.advisor import RetrievedDocument
from app.ai.schemas.retrieval_strategy import (
    RetrievalExecutionPlan,
    RetrievalStrategy,
    SemanticStrategy,
)
from app.ai.semantic.minilm import MiniLMSemanticService
from app.core.config import settings
from app.models.enums import KnowledgeDocumentStatus
from app.models.knowledge import KnowledgeChunk
from app.repositories.knowledge_repository import KnowledgeChunkRepository

logger = logging.getLogger(__name__)


class PostgresRAGRetriever(RAGRetriever):
    """Production vector-similarity & metadata-aware RAG retriever powered by PostgreSQL/pgvector, FAISS, and Adaptive Routing."""

    def __init__(
        self,
        db: Session,
        embedding_provider: EmbeddingProvider,
        top_k: Optional[int] = None,
        similarity_threshold: Optional[float] = None,
        minilm_service: Optional[MiniLMSemanticService] = None,
        faiss_store: Optional[FAISSVectorStore] = None,
    ) -> None:
        self._db = db
        self._embedding_provider = embedding_provider
        self._chunk_repo = KnowledgeChunkRepository(db)
        self.top_k = top_k or settings.rag_top_k
        self.similarity_threshold = similarity_threshold or settings.rag_similarity_threshold

        # Phase J Retrieval Intelligence components
        self._query_processor = QueryProcessor()
        self._reranker = DeterministicReranker()

        # Phase L.4 MiniLM Semantic Intelligence Service
        self._minilm_service = minilm_service or MiniLMSemanticService()

        # Phase L.5 FAISS Vector Store Service
        self._faiss_store = faiss_store or FAISSVectorStore(dimension=settings.embedding_dimension)
        if self._faiss_store.is_available() and not self._faiss_store.is_healthy():
            try:
                self._faiss_store.load()
            except Exception as e:
                logger.warning(f"Failed to auto-load FAISS index store: {e}. FAISS disabled.")

    async def retrieve(
        self,
        query: str,
        filters: Optional[Dict[str, Any]] = None,
        legacy_mode: bool = False,
        retrieval_plan: Optional[RetrievalExecutionPlan] = None,
        tracker: Optional[Any] = None,
        **kwargs: Any,
    ) -> List[RetrievedDocument]:
        """
        Retrieve and rank KnowledgeChunks for user query based on adaptive strategy.

        Args:
            query: Input question or search string.
            filters: Optional dictionary filters (country, category, authority).
            legacy_mode: If True, executes legacy baseline retrieval for comparison evaluation.
            retrieval_plan: Optional Phase L.6 RetrievalExecutionPlan.
            tracker: Optional LatencyTracker instance for profiling.

        Returns:
            List[RetrievedDocument]: Ranked general financial knowledge documents.
        """
        if not query or not query.strip():
            return []

        query_text = query.strip()

        # Legacy baseline retrieval for evaluation comparison
        if legacy_mode:
            return await self._retrieve_legacy(query_text, filters)

        # Apply default plan if none provided
        plan = retrieval_plan or RetrievalExecutionPlan()

        # PHASE L.6 SHORT-CIRCUIT: Strategy NONE returns 0 candidates with 0 retrieval overhead
        if plan.strategy == RetrievalStrategy.NONE:
            if tracker:
                tracker.record_flag("pgvector_used", False)
                tracker.record_flag("faiss_used", False)
                tracker.record_flag("minilm_used", False)
            return []

        # 1. Query Normalization, Synonym Expansion & Historical Intent Detection
        orig_query, norm_query, expanded_terms, is_historical, target_year = self._query_processor.process(query_text)

        # Detect target authority hint from normalized query / expanded terms
        q_lower = orig_query.lower()
        target_authority = None
        if "rbi" in q_lower or "reserve bank" in q_lower or "dicgc" in q_lower:
            target_authority = "RBI"
        elif "sebi" in q_lower or "riskometer" in q_lower or "scores" in q_lower or "demat" in q_lower:
            target_authority = "SEBI"
        elif "tax" in q_lower or "itr" in q_lower or "80c" in q_lower or "80d" in q_lower or "tds" in q_lower or "stcg" in q_lower or "ltcg" in q_lower:
            target_authority = "INCOME_TAX"
        elif "pfrda" in q_lower or "nps" in q_lower:
            target_authority = "PFRDA"
        elif "amfi" in q_lower or "nav" in q_lower or "ter" in q_lower or "sip" in q_lower:
            target_authority = "AMFI"
        elif "ppf" in q_lower or "ssy" in q_lower or "scss" in q_lower:
            target_authority = "GOVERNMENT_OF_INDIA"

        # 2. Generate vector embedding for user query
        query_vector = await self._embedding_provider.embed(norm_query or query_text)

        # 3. Parallel or Selective Candidate Pool Retrieval (pgvector & FAISS)
        pgvector_matches: List[Tuple[KnowledgeChunk, float]] = []
        faiss_results: List[Dict[str, Any]] = []
        pgvector_used = False
        faiss_used = False
        faiss_fallback = False

        pg_k = plan.pgvector_top_k or max(self.top_k * 5, 20)
        faiss_k = plan.faiss_top_k or max(self.top_k * 5, 20)

        def _do_pgvector_search() -> Tuple[List[Tuple[KnowledgeChunk, float]], float]:
            t0 = time.perf_counter()
            try:
                res = self._chunk_repo.search_similarity(
                    query_embedding=query_vector,
                    limit=pg_k,
                    filters=filters,
                    threshold=0.15,
                )
                dur = (time.perf_counter() - t0) * 1000.0
                return res, dur
            except Exception as e:
                logger.error(f"pgvector candidate search failed: {e}")
                dur = (time.perf_counter() - t0) * 1000.0
                return [], dur

        def _do_faiss_search() -> Tuple[List[Dict[str, Any]], float]:
            nonlocal faiss_fallback
            t0 = time.perf_counter()
            if not self._faiss_store.is_healthy():
                return [], 0.0
            try:
                res = self._faiss_store.search(query_embedding=query_vector, top_k=faiss_k)
                dur = (time.perf_counter() - t0) * 1000.0
                return res, dur
            except Exception as e:
                faiss_fallback = True
                logger.warning(f"FAISS search failed: {e}. Falling back cleanly to pgvector.")
                dur = (time.perf_counter() - t0) * 1000.0
                return [], dur

        # Execute searches (concurrently via asyncio.gather if HYBRID strategy)
        if plan.strategy == RetrievalStrategy.HYBRID:
            (pg_res, pg_dur), (faiss_res, faiss_dur) = await asyncio.gather(
                asyncio.to_thread(_do_pgvector_search),
                asyncio.to_thread(_do_faiss_search),
            )
            pgvector_matches = pg_res
            faiss_results = faiss_res
            pgvector_used = len(pgvector_matches) > 0 or plan.strategy == RetrievalStrategy.HYBRID
            faiss_used = len(faiss_results) > 0
            if tracker:
                tracker.record("pgvector_ms", pg_dur)
                tracker.record("faiss_ms", faiss_dur)
        elif plan.strategy == RetrievalStrategy.PGVECTOR_ONLY:
            pgvector_matches, pg_dur = await asyncio.to_thread(_do_pgvector_search)
            pgvector_used = True
            if tracker:
                tracker.record("pgvector_ms", pg_dur)
                tracker.record("faiss_ms", 0.0)
        elif plan.strategy == RetrievalStrategy.FAISS_ONLY:
            faiss_results, faiss_dur = await asyncio.to_thread(_do_faiss_search)
            faiss_used = len(faiss_results) > 0
            if tracker:
                tracker.record("pgvector_ms", 0.0)
                tracker.record("faiss_ms", faiss_dur)

        if tracker:
            tracker.record_flag("pgvector_used", pgvector_used)
            tracker.record_flag("faiss_used", faiss_used)
            tracker.record_count("candidate_count_pgvector", len(pgvector_matches))
            tracker.record_count("candidate_count_faiss", len(faiss_results))

        # If primary chosen strategy produced 0 matches due to DB/FAISS failure, check graceful fallback
        if not pgvector_matches and not faiss_results:
            if plan.strategy == RetrievalStrategy.HYBRID and not pgvector_used and self._faiss_store.is_healthy():
                try:
                    faiss_results, faiss_dur = await asyncio.to_thread(_do_faiss_search)
                    faiss_used = len(faiss_results) > 0
                    if tracker:
                        tracker.record("faiss_ms", faiss_dur)
                        tracker.record_flag("faiss_used", faiss_used)
                        tracker.record_count("candidate_count_faiss", len(faiss_results))
                except Exception:
                    pass
            if not pgvector_matches and not faiss_results:
                return []

        # 3.2 Candidate Fusion via Reciprocal Rank Fusion (RRF)
        t_fusion = time.perf_counter() if tracker else 0.0
        candidate_limit = max(pg_k, faiss_k)
        matches, fusion_meta = self._fuse_candidates(
            pgvector_matches=pgvector_matches,
            faiss_results=faiss_results,
            candidate_limit=candidate_limit,
            rrf_k=plan.rrf_k,
        )
        if tracker and t_fusion > 0.0:
            tracker.record("fusion_ms", (time.perf_counter() - t_fusion) * 1000.0)
            tracker.record_count("candidate_count_fused", len(matches))

        # 3.5 MiniLM Semantic Assistance Scoring on Fused Candidate Pool
        minilm_scores: Optional[List[float]] = None
        minilm_used = False
        if (
            plan.semantic_strategy == SemanticStrategy.MINILM
            and plan.use_minilm
            and self._minilm_service.is_available()
            and matches
        ):
            try:
                candidate_texts = [chunk.content for chunk, _ in matches]
                minilm_scores = self._minilm_service.similarity_to_candidates(
                    query=norm_query or query_text,
                    candidates=candidate_texts,
                    tracker=tracker,
                )
                minilm_used = minilm_scores is not None
            except Exception as e:
                logger.warning(f"MiniLM candidate similarity scoring failed: {e}. Falling back to standard pipeline.")
                minilm_scores = None
                minilm_used = False

        if tracker:
            tracker.record_flag("minilm_used", minilm_used)

        # 4. Deterministic Reranking, Deduplication, Context Diversity, and Abstention Guard
        retrieved = self._reranker.rerank_and_filter(
            matches=matches,
            query_terms=expanded_terms,
            target_authority=target_authority,
            is_historical=is_historical,
            target_year=target_year,
            threshold=self.similarity_threshold,
            top_k=self.top_k,
            minilm_scores=minilm_scores,
            tracker=tracker,
        )

        # Add retrieval execution metadata for observability
        retrieval_summary = {
            "retrieval_strategy": plan.strategy.value,
            "semantic_strategy": plan.semantic_strategy.value,
            "pgvector_used": pgvector_used,
            "faiss_used": faiss_used,
            "minilm_used": minilm_used,
            "pgvector_candidates": len(pgvector_matches),
            "faiss_candidates": len(faiss_results),
            "merged_candidates": len(matches),
            "faiss_fallback": faiss_fallback,
            "fusion_method": "RRF" if plan.use_rrf else "NONE",
            "routing_reason": plan.reason,
        }

        for doc in retrieved:
            doc.metadata["query_normalized"] = norm_query
            doc.metadata["query_expanded_terms"] = expanded_terms
            doc.metadata["is_historical_intent"] = is_historical
            doc.metadata["retrieval_summary"] = retrieval_summary

        return retrieved

    def _fuse_candidates(
        self,
        pgvector_matches: List[Tuple[KnowledgeChunk, float]],
        faiss_results: List[Dict[str, Any]],
        candidate_limit: int,
        rrf_k: Optional[int] = None,
    ) -> Tuple[List[Tuple[KnowledgeChunk, float]], Dict[str, Any]]:

        """
        Perform Reciprocal Rank Fusion (RRF) on pgvector and FAISS candidates.
        
        Returns:
            Tuple containing:
              - Fused list of (KnowledgeChunk, combined_score)
              - Fusion summary dictionary
        """
        if not faiss_results:
            # If FAISS unavailable or yielded 0 candidates, return pgvector matches directly
            return pgvector_matches, {"pgvector_count": len(pgvector_matches), "faiss_count": 0}

        k = rrf_k or settings.faiss_rrf_k
        chunk_map: Dict[str, KnowledgeChunk] = {}
        pg_ranks: Dict[str, int] = {}
        pg_scores: Dict[str, float] = {}
        faiss_ranks: Dict[str, int] = {}
        faiss_scores: Dict[str, float] = {}

        # 1. Index pgvector matches
        for rank, (chunk, score) in enumerate(pgvector_matches, start=1):
            if chunk.document and chunk.document.status != KnowledgeDocumentStatus.ACTIVE:
                continue
            c_id = str(chunk.id)
            chunk_map[c_id] = chunk
            pg_ranks[c_id] = rank
            pg_scores[c_id] = score

        # 2. Index FAISS results & fetch any missing KnowledgeChunks from PostgreSQL
        missing_ids: List[str] = []
        for item in faiss_results:
            c_id = str(item["chunk_id"])
            faiss_ranks[c_id] = item["faiss_rank"]
            faiss_scores[c_id] = item["similarity_score"]
            if c_id not in chunk_map:
                missing_ids.append(c_id)

        if missing_ids:
            try:
                from sqlalchemy import select
                from sqlalchemy.orm import joinedload
                typed_ids = [int(i) if str(i).isdigit() else i for i in missing_ids]
                stmt = (
                    select(KnowledgeChunk)
                    .options(joinedload(KnowledgeChunk.document))
                    .where(KnowledgeChunk.id.in_(typed_ids))
                )
                db_chunks = list(self._db.execute(stmt).scalars().all())
                for chunk in db_chunks:
                    if chunk.document and chunk.document.status == KnowledgeDocumentStatus.ACTIVE:
                        chunk_map[str(chunk.id)] = chunk
            except Exception as e:
                logger.warning(f"Error fetching missing FAISS candidate chunks from DB: {e}")

        # 3. Calculate RRF score for all candidate chunks
        all_chunk_ids = list(chunk_map.keys())
        scored_candidates: List[Tuple[KnowledgeChunk, float]] = []

        for c_id in all_chunk_ids:
            chunk = chunk_map[c_id]
            if chunk.document and chunk.document.status != KnowledgeDocumentStatus.ACTIVE:
                continue
            rrf_score = 0.0

            if c_id in pg_ranks:
                rrf_score += 1.0 / (k + pg_ranks[c_id])
            if c_id in faiss_ranks:
                rrf_score += 1.0 / (k + faiss_ranks[c_id])

            # Select best base vector similarity score between pgvector and FAISS
            base_score = max(pg_scores.get(c_id, 0.0), faiss_scores.get(c_id, 0.0))

            # Store retrieval source breakdown in chunk object transient attribute or metadata
            source_tag = "both" if (c_id in pg_ranks and c_id in faiss_ranks) else ("faiss" if c_id in faiss_ranks else "pgvector")
            chunk._retrieval_source = source_tag
            chunk._rrf_score = round(rrf_score, 6)

            # Combined match score combines base similarity with RRF rank overlap boost
            combined_match_score = min(1.0, round(base_score + (rrf_score * 5.0), 4))
            scored_candidates.append((chunk, combined_match_score))

        # Sort candidates by combined score descending
        scored_candidates.sort(key=lambda x: x[1], reverse=True)
        fused_limit = max(candidate_limit, len(pgvector_matches))
        fused = scored_candidates[:fused_limit]

        fusion_meta = {
            "pgvector_count": len(pgvector_matches),
            "faiss_count": len(faiss_results),
            "fused_count": len(fused),
        }
        return fused, fusion_meta


    async def _retrieve_legacy(
        self, query: str, filters: Optional[Dict[str, Any]] = None
    ) -> List[RetrievedDocument]:
        """Legacy baseline retrieval implementation."""
        query_vector = await self._embedding_provider.embed(query)

        q_lower = query.lower()
        target_authority = None
        if "rbi" in q_lower or "reserve bank" in q_lower:
            target_authority = "RBI"
        elif "sebi" in q_lower or "riskometer" in q_lower:
            target_authority = "SEBI"
        elif "tax" in q_lower or "itr" in q_lower or "80c" in q_lower or "80d" in q_lower or "tds" in q_lower:
            target_authority = "INCOME_TAX"
        elif "pfrda" in q_lower or "nps" in q_lower:
            target_authority = "PFRDA"
        elif "amfi" in q_lower or "nav" in q_lower:
            target_authority = "AMFI"

        matches = self._chunk_repo.search_similarity(
            query_embedding=query_vector,
            limit=max(self.top_k * 3, 15),
            filters=filters,
            threshold=self.similarity_threshold,
        )

        retrieved: List[RetrievedDocument] = []
        for chunk, raw_score in matches:
            doc = chunk.document
            boosted_score = raw_score
            doc_auth_str = str(doc.authority).upper() if doc.authority else ""

            if target_authority and target_authority in doc_auth_str:
                boosted_score = min(1.0, round(raw_score + 0.20, 4))
            elif doc_auth_str in ("RBI", "SEBI", "INCOME_TAX", "PFRDA", "AMFI", "GOVERNMENT_OF_INDIA", "GOVERNMENT", "REGULATOR"):
                boosted_score = min(1.0, round(raw_score + 0.05, 4))

            meta = {
                "chunk_id": chunk.id,
                "chunk_index": chunk.chunk_index,
                "category": doc.category,
                "authority": doc.authority,
                "country": doc.country,
                "jurisdiction": doc.jurisdiction,
                "version": doc.version,
                "effective_date": doc.effective_date.isoformat() if doc.effective_date else None,
                "source_url": doc.source_url,
            }

            retrieved.append(
                RetrievedDocument(
                    document_id=str(doc.id),
                    title=doc.title,
                    content=chunk.content,
                    source=f"{doc.source} ({doc.jurisdiction})",
                    relevance_score=boosted_score,
                    metadata=meta,
                )
            )

        retrieved.sort(key=lambda x: x.relevance_score, reverse=True)
        return retrieved[: self.top_k]
