"""
Production Postgres RAG Retriever implementing the RAGRetriever interface.

Queries KnowledgeChunkRepository using vector embeddings generated by EmbeddingProvider.
"""

from __future__ import annotations

from typing import Dict, List, Optional
from sqlalchemy.orm import Session

from app.ai.providers.base import EmbeddingProvider
from app.ai.rag.base import RAGRetriever
from app.ai.schemas.advisor import RetrievedDocument
from app.core.config import settings
from app.repositories.knowledge_repository import KnowledgeChunkRepository


class PostgresRAGRetriever(RAGRetriever):
    """Production vector-similarity RAG retriever powered by PostgreSQL/pgvector."""

    def __init__(
        self,
        db: Session,
        embedding_provider: EmbeddingProvider,
        top_k: Optional[int] = None,
        similarity_threshold: Optional[float] = None,
    ) -> None:
        self._db = db
        self._embedding_provider = embedding_provider
        self._chunk_repo = KnowledgeChunkRepository(db)
        self.top_k = top_k or settings.rag_top_k
        self.similarity_threshold = similarity_threshold or settings.rag_similarity_threshold

    async def retrieve(
        self, query: str, filters: Optional[Dict[str, Any]] = None
    ) -> List[RetrievedDocument]:
        """
        Convert query to embedding vector and search pgvector for closest chunks.

        Args:
            query: Input question or search string.
            filters: Optional dictionary filters (country, category, authority).

        Returns:
            List[RetrievedDocument]: Ranked general financial knowledge documents.
        """
        if not query or not query.strip():
            return []

        # 1. Generate vector embedding for user query
        query_vector = await self._embedding_provider.embed(query.strip())

        # 2. Perform similarity search against active RAG chunks
        matches = self._chunk_repo.search_similarity(
            query_embedding=query_vector,
            limit=self.top_k,
            filters=filters,
            threshold=self.similarity_threshold,
        )

        # 3. Map KnowledgeChunk matches to RetrievedDocument schema
        retrieved: List[RetrievedDocument] = []
        for chunk, score in matches:
            doc = chunk.document
            meta = {
                "chunk_id": chunk.id,
                "chunk_index": chunk.chunk_index,
                "category": doc.category,
                "authority": doc.authority,
                "country": doc.country,
                "jurisdiction": doc.jurisdiction,
                "version": doc.version,
                "effective_date": doc.effective_date.isoformat() if doc.effective_date else None,
                "source_url": doc.source_url,
            }
            if chunk.chunk_metadata:
                meta.update(chunk.chunk_metadata)

            retrieved.append(
                RetrievedDocument(
                    document_id=str(doc.id),
                    title=doc.title,
                    content=chunk.content,
                    source=f"{doc.source} ({doc.jurisdiction})",
                    relevance_score=score,
                    metadata=meta,
                )
            )

        return retrieved
