"""
Conversation and ConversationMessage models for DhanSarthi AI Advisor.

Each Conversation belongs to exactly one authenticated user.
ConversationMessage records individual turns (USER / ASSISTANT) within a thread.

Security invariants:
  - Conversation.user_id enforces ownership scoping.
  - No cross-user access is possible through the model layer alone.
  - Messages are accessed only via their parent conversation (never by message_id alone).
  - Soft deletion via deleted_at follows the project's SoftDeleteMixin pattern.
"""

from __future__ import annotations

from datetime import datetime
from typing import List, Optional

from sqlalchemy import (
    BigInteger,
    DateTime,
    Enum as SAEnum,
    ForeignKey,
    Index,
    Integer,
    JSON,
    String,
    Text,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.enums import ConversationStatus, MessageRole
from app.models.mixins import TimestampMixin, pk_column


class Conversation(Base, TimestampMixin):
    """An AI conversation thread owned by a single authenticated user.

    Soft delete is used (deleted_at) to preserve message history for
    auditing and future restoration without physical data loss.
    """

    __tablename__ = "conversations"
    __table_args__ = (
        Index("ix_conversations_user_id", "user_id"),
        Index("ix_conversations_user_status", "user_id", "status"),
        Index("ix_conversations_updated_at", "updated_at"),
    )

    id: Mapped[int] = pk_column()
    user_id: Mapped[int] = mapped_column(
        BigInteger().with_variant(Integer, "sqlite"),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(String(200), nullable=False, default="New Conversation")
    status: Mapped[ConversationStatus] = mapped_column(
        SAEnum(ConversationStatus, native_enum=False, validate_strings=True, length=20),
        nullable=False,
        default=ConversationStatus.ACTIVE,
    )
    deleted_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True, default=None
    )

    messages: Mapped[List[ConversationMessage]] = relationship(
        "ConversationMessage",
        back_populates="conversation",
        cascade="all, delete-orphan",
        order_by="ConversationMessage.created_at",
    )

    def __repr__(self) -> str:
        return f"<Conversation id={self.id} user_id={self.user_id} title={self.title!r}>"


class ConversationMessage(Base, TimestampMixin):
    """A single message turn in a conversation thread.

    Roles:
      USER      — message submitted by the authenticated user.
      ASSISTANT — response generated by the DhanSarthi AI Advisor.

    message_metadata stores safe operational fields only:
      model, provider, response_time_ms, source_ids, retrieval_count.
    Never stores API keys, raw prompts, or full financial context.
    """

    __tablename__ = "conversation_messages"
    __table_args__ = (
        Index("ix_conv_messages_conversation_id", "conversation_id"),
        Index("ix_conv_messages_created_at", "created_at"),
    )

    id: Mapped[int] = pk_column()
    conversation_id: Mapped[int] = mapped_column(
        BigInteger().with_variant(Integer, "sqlite"),
        ForeignKey("conversations.id", ondelete="CASCADE"),
        nullable=False,
    )
    role: Mapped[MessageRole] = mapped_column(
        SAEnum(MessageRole, native_enum=False, validate_strings=True, length=15),
        nullable=False,
    )
    content: Mapped[str] = mapped_column(Text, nullable=False)
    message_metadata: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    conversation: Mapped[Conversation] = relationship(
        "Conversation",
        back_populates="messages",
    )

    def __repr__(self) -> str:
        return (
            f"<ConversationMessage id={self.id} "
            f"conv_id={self.conversation_id} role={self.role}>"
        )
