export const ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  profile: {
    get: '/profile',
    create: '/profile',
    update: '/profile',
  },
  income: {
    list: '/income',
    create: '/income',
    get: (id) => `/income/${id}`,
    update: (id) => `/income/${id}`,
    delete: (id) => `/income/${id}`,
  },
  expenses: {
    list: '/expenses',
    create: '/expenses',
    get: (id) => `/expenses/${id}`,
    update: (id) => `/expenses/${id}`,
    delete: (id) => `/expenses/${id}`,
  },
  transactions: {
    list: '/transactions',
    create: '/transactions',
    get: (id) => `/transactions/${id}`,
    update: (id) => `/transactions/${id}`,
    delete: (id) => `/transactions/${id}`,
  },
  assets: {
    list: '/assets',
    create: '/assets',
    get: (id) => `/assets/${id}`,
    update: (id) => `/assets/${id}`,
    delete: (id) => `/assets/${id}`,
  },
  liabilities: {
    list: '/liabilities',
    create: '/liabilities',
    get: (id) => `/liabilities/${id}`,
    update: (id) => `/liabilities/${id}`,
    delete: (id) => `/liabilities/${id}`,
  },
  loans: {
    list: '/loans',
    create: '/loans',
    get: (id) => `/loans/${id}`,
    update: (id) => `/loans/${id}`,
    delete: (id) => `/loans/${id}`,
    listPayments: (loanId) => `/loans/${loanId}/payments`,
    createPayment: (loanId) => `/loans/${loanId}/payments`,
    getPayment: (loanId, paymentId) => `/loans/${loanId}/payments/${paymentId}`,
  },
  investments: {
    list: '/investments',
    create: '/investments',
    get: (id) => `/investments/${id}`,
    update: (id) => `/investments/${id}`,
    delete: (id) => `/investments/${id}`,
    listTransactions: (investmentId) => `/investments/${investmentId}/transactions`,
    createTransaction: (investmentId) => `/investments/${investmentId}/transactions`,
    getTransaction: (investmentId, transactionId) =>
      `/investments/${investmentId}/transactions/${transactionId}`,
  },
  budgets: {
    list: '/budgets',
    create: '/budgets',
    get: (id) => `/budgets/${id}`,
    update: (id) => `/budgets/${id}`,
    delete: (id) => `/budgets/${id}`,
  },
  goals: {
    list: '/goals',
    create: '/goals',
    get: (id) => `/goals/${id}`,
    update: (id) => `/goals/${id}`,
    delete: (id) => `/goals/${id}`,
  },
  dashboard: {
    get: '/dashboard',
  },
  financial: {
    summary: '/financial/summary',
    cashFlow: '/financial/cash-flow',
    savings: '/financial/savings',
    netWorth: '/financial/net-worth',
    debt: '/financial/debt',
    investmentsSummary: '/financial/investments/summary',
    loanCalculate: '/financial/loan/calculate',
    sipCalculate: '/financial/investments/sip/calculate',
    budget: '/financial/budget',
    goals: '/financial/goals',
    context: '/financial/context',
  },
  financialIntelligence: {
    summary: '/financial-intelligence/summary',
    cashFlow: '/financial-intelligence/cash-flow',
    debt: '/financial-intelligence/debt',
    investments: '/financial-intelligence/investments',
    goals: '/financial-intelligence/goals',
    loanScenario: '/financial-intelligence/loan-scenario',
    scenario: '/financial-intelligence/scenario',
  },
  ai: {
    advisor: '/ai/advisor',
    conversations: {
      list: '/ai/conversations',
      create: '/ai/conversations',
      get: (id) => `/ai/conversations/${id}`,
      delete: (id) => `/ai/conversations/${id}`,
      sendMessage: (id) => `/ai/conversations/${id}/messages`,
      stream: (id) => `/ai/conversations/${id}/stream`,
    },
  },
  documents: {
    upload: '/documents',
    list: '/documents',
    get: (id) => `/documents/${id}`,
    delete: (id) => `/documents/${id}`,
    process: (id) => `/documents/${id}/process`,
    extraction: (id) => `/documents/${id}/extraction`,
    confirm: (id) => `/documents/${id}/confirm`,
  },
  market: {
    stocksSearch: '/market/stocks/search',
    stocksQuote: (symbol) => `/market/stocks/${symbol}`,
    mutualFundsSearch: '/market/mutual-funds/search',
    mutualFundsNav: (schemeId) => `/market/mutual-funds/${schemeId}/nav`,
    fxRate: (base, quote) => `/market/fx/${base}/${quote}`,
    indexQuote: (indexName) => `/market/indices/${indexName}`,
    interestRates: (country, typeName) => `/market/interest-rates/${country}/${typeName}`,
    portfolioEstimated: '/market/portfolio/estimated',
  },
  reports: {
    export: '/reports/export',
  },
}

export default ENDPOINTS
