export const navigationConfig = {
  Student: [
    {
      label: 'Dashboard',
      icon: 'LayoutDashboard',
      path: '/dashboard',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
    {
      label: 'Profile',
      icon: 'User',
      path: '/profile',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
    {
      label: 'Finance',
      icon: 'Wallet',
      path: '/finance',
      permission: null,
      children: null,
      badge: 'Goal Tracking',
      featureFlag: null,
    },
    {
      label: 'Investments',
      icon: 'TrendingUp',
      path: '/investments',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
    {
      label: 'AI Advisor',
      icon: 'Bot',
      path: '/ai-advisor',
      permission: null,
      children: null,
      badge: 'AI-First',
      featureFlag: null,
    },
    {
      label: 'Reports',
      icon: 'FileText',
      path: '/reports',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
    {
      label: 'Settings',
      icon: 'Settings',
      path: '/settings',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
  ],
  'Working Professional': [
    {
      label: 'Dashboard',
      icon: 'LayoutDashboard',
      path: '/dashboard',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
    {
      label: 'Profile',
      icon: 'User',
      path: '/profile',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
    {
      label: 'Finance',
      icon: 'Wallet',
      path: '/finance',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
    {
      label: 'Investments',
      icon: 'TrendingUp',
      path: '/investments',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
    {
      label: 'AI Advisor',
      icon: 'Bot',
      path: '/ai-advisor',
      permission: null,
      children: null,
      badge: 'AI-First',
      featureFlag: null,
    },
    {
      label: 'Reports',
      icon: 'FileText',
      path: '/reports',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
    {
      label: 'Settings',
      icon: 'Settings',
      path: '/settings',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
  ],
  Business: [
    {
      label: 'Dashboard',
      icon: 'LayoutDashboard',
      path: '/dashboard',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
    {
      label: 'Profile',
      icon: 'User',
      path: '/profile',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
    {
      label: 'Finance',
      icon: 'Wallet',
      path: '/finance',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
    {
      label: 'Investments',
      icon: 'TrendingUp',
      path: '/investments',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
    {
      label: 'AI Advisor',
      icon: 'Bot',
      path: '/ai-advisor',
      permission: null,
      children: null,
      badge: 'AI-First',
      featureFlag: null,
    },
    {
      label: 'Reports',
      icon: 'FileText',
      path: '/reports',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
    {
      label: 'Settings',
      icon: 'Settings',
      path: '/settings',
      permission: null,
      children: null,
      badge: null,
      featureFlag: null,
    },
  ],
};

export default navigationConfig;
