"""initial_base

Revision ID: 14d52cffd3cd
Revises: 
Create Date: 2026-08-09 17:34:14.688596
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '14d52cffd3cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
