"""add_password_hash_to_users

Revision ID: c3f8be1f809b
Revises: 9d8f86839e0e
Create Date: 2026-08-11 12:59:48.262009
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = 'c3f8be1f809b'
down_revision: Union[str, Sequence[str], None] = '9d8f86839e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
