from functools import lru_cache

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="ignore")

    app_name: str = Field(default="DhanSarthi API", validation_alias="APP_NAME")
    app_env: str = Field(default="development", validation_alias="APP_ENV")
    database_url: str = Field(validation_alias="DATABASE_URL")
    database_pool_size: int = Field(default=5, validation_alias="DATABASE_POOL_SIZE")
    database_max_overflow: int = Field(default=10, validation_alias="DATABASE_MAX_OVERFLOW")
    api_v1_prefix: str = Field(default="/api/v1", validation_alias="API_V1_PREFIX")
    cors_origins: str = Field(default="http://localhost:5173", validation_alias="CORS_ORIGINS")
    ai_provider_api_key: str | None = Field(default=None, validation_alias="AI_PROVIDER_API_KEY")
    embedding_provider_api_key: str | None = Field(default=None, validation_alias="EMBEDDING_PROVIDER_API_KEY")
    ai_provider: str = Field(default="mock", validation_alias="AI_PROVIDER")
    ai_model: str = Field(default="meta-llama/Meta-Llama-3-8B-Instruct", validation_alias="AI_MODEL")
    ai_max_tokens: int = Field(default=1024, validation_alias="AI_MAX_TOKENS")
    ai_temperature: float = Field(default=0.2, validation_alias="AI_TEMPERATURE")
    rag_top_k: int = Field(default=5, validation_alias="RAG_TOP_K")
    rag_similarity_threshold: float = Field(default=0.3, validation_alias="RAG_SIMILARITY_THRESHOLD")
    rag_max_context_tokens: int = Field(default=2000, validation_alias="RAG_MAX_CONTEXT_TOKENS")
    rag_chunk_size: int = Field(default=500, validation_alias="RAG_CHUNK_SIZE")
    rag_chunk_overlap: int = Field(default=50, validation_alias="RAG_CHUNK_OVERLAP")
    embedding_provider: str = Field(default="mock", validation_alias="EMBEDDING_PROVIDER")
    embedding_model: str = Field(default="sentence-transformers/all-MiniLM-L6-v2", validation_alias="EMBEDDING_MODEL")
    embedding_dimension: int = Field(default=384, validation_alias="EMBEDDING_DIMENSION")

    minilm_enabled: bool = Field(default=True, validation_alias="MINILM_ENABLED")
    minilm_model: str = Field(default="sentence-transformers/all-MiniLM-L6-v2", validation_alias="MINILM_MODEL")
    minilm_similarity_weight: float = Field(default=0.20, validation_alias="MINILM_SIMILARITY_WEIGHT")
    minilm_max_candidates: int = Field(default=20, validation_alias="MINILM_MAX_CANDIDATES")
    minilm_timeout_seconds: float = Field(default=2.0, validation_alias="MINILM_TIMEOUT_SECONDS")

    faiss_enabled: bool = Field(default=True, validation_alias="FAISS_ENABLED")
    faiss_index_path: str = Field(default="./data/faiss/knowledge.index", validation_alias="FAISS_INDEX_PATH")
    faiss_mapping_path: str = Field(default="./data/faiss/knowledge_mapping.json", validation_alias="FAISS_MAPPING_PATH")
    faiss_metadata_path: str = Field(default="./data/faiss/knowledge_metadata.json", validation_alias="FAISS_METADATA_PATH")
    faiss_top_k: int = Field(default=20, validation_alias="FAISS_TOP_K")
    faiss_rrf_k: int = Field(default=60, validation_alias="FAISS_RRF_K")
    faiss_auto_rebuild: bool = Field(default=False, validation_alias="FAISS_AUTO_REBUILD")
    storage_bucket: str | None = Field(default=None, validation_alias="STORAGE_BUCKET")
    secret_key: str | None = Field(default=None, validation_alias="SECRET_KEY")
    auth_jwt_secret: str | None = Field(default=None, validation_alias="AUTH_JWT_SECRET")
    auth_jwt_algorithm: str = Field(default="HS256", validation_alias="AUTH_JWT_ALGORITHM")
    auth_access_token_expire_minutes: int = Field(default=30, validation_alias="AUTH_ACCESS_TOKEN_EXPIRE_MINUTES")
    ai_max_history_messages: int = Field(default=20, validation_alias="AI_MAX_HISTORY_MESSAGES")
    ai_request_timeout_seconds: int = Field(default=60, validation_alias="AI_REQUEST_TIMEOUT_SECONDS")
    ai_max_message_length: int = Field(default=2000, validation_alias="AI_MAX_MESSAGE_LENGTH")
    ai_rate_limit_requests: int = Field(default=30, validation_alias="AI_RATE_LIMIT_REQUESTS")
    ai_rate_limit_window_seconds: int = Field(default=60, validation_alias="AI_RATE_LIMIT_WINDOW_SECONDS")
    max_document_size_mb: int = Field(default=10, validation_alias="MAX_DOCUMENT_SIZE_MB")
    document_storage_path: str = Field(default="storage/documents", validation_alias="DOCUMENT_STORAGE_PATH")
    document_max_pages: int = Field(default=100, validation_alias="DOCUMENT_MAX_PAGES")
    document_classification_threshold: float = Field(default=0.6, validation_alias="DOCUMENT_CLASSIFICATION_THRESHOLD")
    dti_threshold_high: float = Field(default=36.0, validation_alias="DTI_THRESHOLD_HIGH")
    dti_threshold_very_high: float = Field(default=50.0, validation_alias="DTI_THRESHOLD_VERY_HIGH")
    emergency_fund_target_months: int = Field(default=6, validation_alias="EMERGENCY_FUND_TARGET_MONTHS")
    emergency_fund_warning_months: int = Field(default=3, validation_alias="EMERGENCY_FUND_WARNING_MONTHS")
    budget_utilization_warning_percent: float = Field(default=85.0, validation_alias="BUDGET_UTILIZATION_WARNING_PERCENT")
    investment_concentration_threshold: float = Field(default=50.0, validation_alias="INVESTMENT_CONCENTRATION_THRESHOLD")

    market_data_provider: str = Field(default="mock", validation_alias="MARKET_DATA_PROVIDER")
    stock_data_api_key: str | None = Field(default=None, validation_alias="STOCK_DATA_API_KEY")
    stock_data_provider: str = Field(default="mock", validation_alias="STOCK_DATA_PROVIDER")
    mutual_fund_provider: str = Field(default="mock", validation_alias="MUTUAL_FUND_PROVIDER")
    fx_provider: str = Field(default="mock", validation_alias="FX_PROVIDER")
    index_provider: str = Field(default="mock", validation_alias="INDEX_PROVIDER")
    interest_rate_provider: str = Field(default="mock", validation_alias="INTEREST_RATE_PROVIDER")
    market_data_cache_ttl_stock: int = Field(default=300, validation_alias="MARKET_DATA_CACHE_TTL_STOCK")
    market_data_cache_ttl_nav: int = Field(default=43200, validation_alias="MARKET_DATA_CACHE_TTL_NAV")
    market_data_cache_ttl_fx: int = Field(default=3600, validation_alias="MARKET_DATA_CACHE_TTL_FX")
    market_data_cache_ttl_index: int = Field(default=300, validation_alias="MARKET_DATA_CACHE_TTL_INDEX")
    market_data_cache_ttl_rate: int = Field(default=86400, validation_alias="MARKET_DATA_CACHE_TTL_RATE")

    adaptive_retrieval_enabled: bool = Field(default=True, validation_alias="ADAPTIVE_RETRIEVAL_ENABLED")
    adaptive_default_pgvector_k: int = Field(default=20, validation_alias="ADAPTIVE_DEFAULT_PGVECTOR_K")
    adaptive_default_faiss_k: int = Field(default=20, validation_alias="ADAPTIVE_DEFAULT_FAISS_K")
    adaptive_comparison_k: int = Field(default=25, validation_alias="ADAPTIVE_COMPARISON_K")
    adaptive_authority_k: int = Field(default=25, validation_alias="ADAPTIVE_AUTHORITY_K")
    adaptive_historical_k: int = Field(default=25, validation_alias="ADAPTIVE_HISTORICAL_K")
    adaptive_definition_k: int = Field(default=15, validation_alias="ADAPTIVE_DEFINITION_K")
    adaptive_rrf_k_default: int = Field(default=60, validation_alias="ADAPTIVE_RRF_K_DEFAULT")
    adaptive_rrf_k_comparison: int = Field(default=40, validation_alias="ADAPTIVE_RRF_K_COMPARISON")
    adaptive_rrf_k_authority: int = Field(default=50, validation_alias="ADAPTIVE_RRF_K_AUTHORITY")

    ai_max_tokens_casual: int = Field(default=128, validation_alias="AI_MAX_TOKENS_CASUAL")
    ai_max_tokens_simple_general: int = Field(default=256, validation_alias="AI_MAX_TOKENS_SIMPLE_GENERAL")
    ai_max_tokens_personal_lookup: int = Field(default=300, validation_alias="AI_MAX_TOKENS_PERSONAL_LOOKUP")
    ai_max_tokens_mixed: int = Field(default=450, validation_alias="AI_MAX_TOKENS_MIXED")
    ai_max_tokens_comparison: int = Field(default=600, validation_alias="AI_MAX_TOKENS_COMPARISON")
    ai_max_tokens_historical: int = Field(default=600, validation_alias="AI_MAX_TOKENS_HISTORICAL")
    ai_max_tokens_analysis: int = Field(default=800, validation_alias="AI_MAX_TOKENS_ANALYSIS")
    ai_max_tokens_global_safety_max: int = Field(default=1024, validation_alias="AI_MAX_TOKENS_GLOBAL_SAFETY_MAX")

    ai_cache_educational_enabled: bool = Field(default=True, validation_alias="AI_CACHE_EDUCATIONAL_ENABLED")
    ai_cache_educational_ttl_seconds: int = Field(default=3600, validation_alias="AI_CACHE_EDUCATIONAL_TTL_SECONDS")
    ai_cache_educational_max_entries: int = Field(default=200, validation_alias="AI_CACHE_EDUCATIONAL_MAX_ENTRIES")
    ai_response_cache_enabled: bool = Field(default=True, validation_alias="AI_RESPONSE_CACHE_ENABLED")
    ai_response_cache_ttl_seconds: int = Field(default=3600, validation_alias="AI_RESPONSE_CACHE_TTL_SECONDS")
    ai_response_cache_max_entries: int = Field(default=500, validation_alias="AI_RESPONSE_CACHE_MAX_ENTRIES")
    ai_response_cache_version: str = Field(default="v1", validation_alias="AI_RESPONSE_CACHE_VERSION")
    ai_response_cache_prompt_version: str = Field(default="v1", validation_alias="AI_RESPONSE_CACHE_PROMPT_VERSION")
    ai_response_cache_knowledge_version: str = Field(default="v1", validation_alias="AI_RESPONSE_CACHE_KNOWLEDGE_VERSION")
    ai_response_cache_policy_version: str = Field(default="v1", validation_alias="AI_RESPONSE_CACHE_POLICY_VERSION")

    ai_prompt_max_history_messages: int = Field(default=6, validation_alias="AI_PROMPT_MAX_HISTORY_MESSAGES")

    ai_http_max_connections: int = Field(default=20, validation_alias="AI_HTTP_MAX_CONNECTIONS")
    ai_http_max_keepalive_connections: int = Field(default=10, validation_alias="AI_HTTP_MAX_KEEPALIVE_CONNECTIONS")
    ai_http_keepalive_seconds: float = Field(default=30.0, validation_alias="AI_HTTP_KEEPALIVE_SECONDS")
    ai_max_retries: int = Field(default=1, validation_alias="AI_MAX_RETRIES")

    # Phase L.7.3 / L.9.8 — Streaming
    ai_streaming_enabled: bool = Field(default=False, validation_alias="AI_STREAMING_ENABLED")
    ai_streaming_default: bool = Field(default=True, validation_alias="AI_STREAMING_DEFAULT")
    ai_streaming_first_enabled: bool = Field(default=True, validation_alias="AI_STREAMING_FIRST_ENABLED")
    ai_streaming_fallback_enabled: bool = Field(default=True, validation_alias="AI_STREAMING_FALLBACK_ENABLED")
    ai_streaming_heartbeat_seconds: float = Field(default=15.0, validation_alias="AI_STREAMING_HEARTBEAT_SECONDS")
    ai_streaming_max_duration_seconds: int = Field(default=90, validation_alias="AI_STREAMING_MAX_DURATION_SECONDS")

    ai_adaptive_inference_enabled: bool = Field(default=True, validation_alias="AI_ADAPTIVE_INFERENCE_ENABLED")
    ai_simple_max_tokens: int = Field(default=256, validation_alias="AI_SIMPLE_MAX_TOKENS")
    ai_moderate_max_tokens: int = Field(default=512, validation_alias="AI_MODERATE_MAX_TOKENS")
    ai_complex_max_tokens: int = Field(default=768, validation_alias="AI_COMPLEX_MAX_TOKENS")
    ai_max_context_chars: int = Field(default=12000, validation_alias="AI_MAX_CONTEXT_CHARS")
    ai_max_rag_context_chars: int = Field(default=7000, validation_alias="AI_MAX_RAG_CONTEXT_CHARS")
    ai_max_personal_context_chars: int = Field(default=4000, validation_alias="AI_MAX_PERSONAL_CONTEXT_CHARS")
    ai_max_history_chars: int = Field(default=5000, validation_alias="AI_MAX_HISTORY_CHARS")

    ai_model_routing_enabled: bool = Field(default=False, validation_alias="AI_MODEL_ROUTING_ENABLED")
    ai_fast_model: str = Field(default="meta-llama/Meta-Llama-3-8B-Instruct", validation_alias="AI_FAST_MODEL")
    ai_balanced_model: str = Field(default="meta-llama/Meta-Llama-3-8B-Instruct", validation_alias="AI_BALANCED_MODEL")
    ai_reasoning_model: str = Field(default="meta-llama/Meta-Llama-3-8B-Instruct", validation_alias="AI_REASONING_MODEL")
    ai_allowed_models: str = Field(default="meta-llama/Meta-Llama-3-8B-Instruct,meta-llama/Llama-3.2-1B-Instruct,meta-llama/Llama-3.2-3B-Instruct,Qwen/Qwen2.5-7B-Instruct", validation_alias="AI_ALLOWED_MODELS")
    ai_tokenizer_model: str = Field(default="meta-llama/Meta-Llama-3-8B-Instruct", validation_alias="AI_TOKENIZER_MODEL")
    ai_provider_readiness_fallback_model: str = Field(default="", validation_alias="AI_PROVIDER_READINESS_FALLBACK_MODEL")

    ai_prompt_compression_enabled: bool = Field(default=True, validation_alias="AI_PROMPT_COMPRESSION_ENABLED")
    ai_prompt_compression_mode: str = Field(default="adaptive", validation_alias="AI_PROMPT_COMPRESSION_MODE")
    ai_max_prompt_tokens: int = Field(default=2048, validation_alias="AI_MAX_PROMPT_TOKENS")
    ai_max_rag_chunks_after_compression: int = Field(default=3, validation_alias="AI_MAX_RAG_CHUNKS_AFTER_COMPRESSION")
    ai_rag_dedup_similarity_threshold: float = Field(default=0.65, validation_alias="AI_RAG_DEDUP_SIMILARITY_THRESHOLD")
    ai_max_history_messages_after_compression: int = Field(default=4, validation_alias="AI_MAX_HISTORY_MESSAGES_AFTER_COMPRESSION")
    ai_prompt_compression_version: str = Field(default="v1", validation_alias="AI_PROMPT_COMPRESSION_VERSION")

    # Phase L.9.9 — AI Production Resilience, Failure Recovery & Graceful Degradation
    ai_resilience_enabled: bool = Field(default=True, validation_alias="AI_RESILIENCE_ENABLED")
    ai_max_total_attempts: int = Field(default=3, validation_alias="AI_MAX_TOTAL_ATTEMPTS")
    ai_circuit_breaker_enabled: bool = Field(default=True, validation_alias="AI_CIRCUIT_BREAKER_ENABLED")
    ai_circuit_failure_threshold: int = Field(default=5, validation_alias="AI_CIRCUIT_FAILURE_THRESHOLD")
    ai_circuit_recovery_seconds: float = Field(default=30.0, validation_alias="AI_CIRCUIT_RECOVERY_SECONDS")
    ai_circuit_half_open_requests: int = Field(default=1, validation_alias="AI_CIRCUIT_HALF_OPEN_REQUESTS")
    ai_resilience_max_backoff_seconds: float = Field(default=4.0, validation_alias="AI_RESILIENCE_MAX_BACKOFF_SECONDS")
    ai_resilience_jitter_seconds: float = Field(default=0.25, validation_alias="AI_RESILIENCE_JITTER_SECONDS")
    ai_provider_fallback_enabled: bool = Field(default=True, validation_alias="AI_PROVIDER_FALLBACK_ENABLED")
    ai_rag_degradation_enabled: bool = Field(default=True, validation_alias="AI_RAG_DEGRADATION_ENABLED")
    ai_stream_recovery_enabled: bool = Field(default=True, validation_alias="AI_STREAM_RECOVERY_ENABLED")

    # Phase L.10 — Production AI Observability, Evaluation & Performance Monitoring
    ai_observability_enabled: bool = Field(default=True, validation_alias="AI_OBSERVABILITY_ENABLED")
    ai_observability_retention_hours: int = Field(default=24, validation_alias="AI_OBSERVABILITY_RETENTION_HOURS")
    ai_observability_max_events: int = Field(default=10000, validation_alias="AI_OBSERVABILITY_MAX_EVENTS")
    ai_health_p95_latency_ms: float = Field(default=20000.0, validation_alias="AI_HEALTH_P95_LATENCY_MS")
    ai_health_min_quality_score: float = Field(default=0.90, validation_alias="AI_HEALTH_MIN_QUALITY_SCORE")
    ai_health_min_citation_accuracy: float = Field(default=0.95, validation_alias="AI_HEALTH_MIN_CITATION_ACCURACY")
    ai_health_min_grounding_score: float = Field(default=0.95, validation_alias="AI_HEALTH_MIN_GROUNDING_SCORE")
    ai_health_max_fallback_rate: float = Field(default=0.10, validation_alias="AI_HEALTH_MAX_FALLBACK_RATE")
    ai_health_max_retry_rate: float = Field(default=0.20, validation_alias="AI_HEALTH_MAX_RETRY_RATE")
    ai_health_max_stream_interruption_rate: float = Field(default=0.05, validation_alias="AI_HEALTH_MAX_STREAM_INTERRUPTION_RATE")
    ai_observability_api_enabled: bool = Field(default=True, validation_alias="AI_OBSERVABILITY_API_ENABLED")

    @property
    def cors_origins_list(self) -> list[str]:
        return [origin.strip() for origin in self.cors_origins.split(",") if origin.strip()]


@lru_cache
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
